kind: Inventory
data:
  - name: slot_flags
    _ref: <Slot>
    _flags:
    - '[CL]'
  - name: fv_classes
    _ref: <FV>
    _flags:
    - '[aɔ]'
    - '[ao]'
    - '[ai]'
    - '[ɔɔ]'
    - '[ɔu]'
    - '[ɔi]'
  - name: accusative_markers
    _ref: <ACC>
    _flags:
    - '[-a]'
    - '[-ɛ]'
    - '[-ɔ]'
    - '[-ŋù]'
    - '[-ɲa]'
