kind: Inventory
data:
  slot_flags:
    _ref: <Slot>
    _flags:
    - '[CL]'
  fv_classes:
    _ref: <FV>
    _flags:
    - '[aɔ]'
    - '[ao]'
    - '[ai]'
    - '[ɔɔ]'
    - '[ɔu]'
    - '[ɔi]'
  accusative_markers:
    _ref: <ACC>
    _flags:
    - '[-a]'
    - '[-ɛ]'
    - '[-ɔ]'
    - '[-ŋù]'
    - '[-ɲa]'
