kind: Inventory
data:
  - _ref: consonants
    _ref: <C>
    _children:
    - _ref: stops
      _ref: <Plsv>
      _children:
        - _ref: voiced
          _ref: <B>
          _phones:
          - b
          - d̪
          - d
          - ɟ
          - g
        - _ref: voiceless
          _ref: <P>
          _phones:
          - p
          - t̪
          - t
          - c
          - k
          - ʔ
    - _ref: nasals
      _ref: <N>
      _phones:
      - m
      - n
      - ɲ
      - ŋ
    - _ref: fricatives
      _ref: <F>
      _phones:
      - f
      - v
      - ð
      - s
      - ʃ
      - h
    - _ref: resonants
      _ref: <R>
      _phones:
      - r
      - ɾ
      - ɽ
      - l
      - w
      - j
  - _ref: vowels
    _ref: <V>
    _children:
    - _ref: high
      _ref: <V_High>
      _phones:
      - i
      - ɪ
      - u
      - ʊ
    - _ref: mid
      _ref: <V_Mid>
      _phones:
      - e
      - ɛ
      - ə
      - ɜ
      - o
      - ɔ
    - _ref: low
      _ref: <V_Low>
      _phones:
      - a
