kind: Inventory
data:
  consonants:
    _ref: <C>
    stops:
      _ref: <Plsv>
      voiced:
        _ref: <B>
        _phones:
        - b
        - d̪
        - d
        - ɟ
        - g
      voiceless:
        _ref: <P>
        _phones:
        - p
        - t̪
        - t
        - c
        - k
        - ʔ
    nasals:
      _ref: <N>
      _phones:
      - m
      - n
      - ɲ
      - ŋ
    fricatives:
      _ref: <F>
      _phones:
      - f
      - v
      - ð
      - s
      - ʃ
      - h
    resonants:
      _ref: <R>
      _phones:
      - r
      - ɾ
      - ɽ
      - l
      - w
      - j
  vowels:
    _ref: <V>
    high:
      _ref: <V_High>
      _phones:
      - i
      - ɪ
      - u
      - ʊ
    mid:
      _ref: <V_Mid>
      _phones:
      - e
      - ɛ
      - ə
      - ɜ
      - o
      - ɔ
    low:
      _ref: <V_Low>
      _phones:
      - a
