kind: Inventory
data:
- _ref: <TONE_SLOT>
  name: Tone flags
  _flags:
  - '[TBU]'
  - '[FLOAT]'
- _ref: <T>
  name: Tones
  _children:
  - _ref: <HL>
    name: Falling
    _phones:
    - ̂
  - _ref: <H>
    name: High
    _phones:
    - ́
  - _ref: <L>
    name: Low
    _phones:
    - ̀
  - _ref: <LH>
    name: Rising
    _phones:
    - ̌
