kind: Paradigm
part_of_speech: $verb
order:
- tone_melody
feature_markers: {}
contingent_markers:
- $tam_deixis_tone
filter:
  lexical_features: []
global_markers:
- type: rule
  value: $resolve_hiatus
  order: hiatus_resolution
