kind: Rules
rules:
  ipfv_it_fv:
    string_map:
    - - '{[aɔ][ao][ai]}'
      - -à
    - - '{[ɔɔ][ɔi][ɔu]}'
      - -ɔ̀
    test_mappings:
    - - vəlɛð[aɔ]
      - vəlɛð-à
    - - kɜc[ɔi]
      - kɜc-ɔ̀
    - - ilɛð[ɔɔ]
      - ilɛð-ɔ̀
  ipfv_pfv_vent_fv:
    string_map:
    - - '{[aɔ][ɔɔ]}'
      - -ɔ́
    - - '[ao]'
      - -ó
    - - '[ɔu]'
      - -ú
    - - '{[ai][ɔi]}'
      - -í
    test_mappings:
    - - vəlɛð[aɔ]
      - vəlɛð-ɔ́
    - - kɜc[ɔi]
      - kɜc-í
    - - ilɛð[ɔɔ]
      - ilɛð-ɔ́
  pfv_it_fv:
    string_map:
    - - '{[aɔ][ɔɔ]}'
      - -ɛ̀
    - - '{[ao][ɔu][ai][ɔi]}'
      - -ì
    test_mappings:
    - - vəlɛð[aɔ]
      - vəlɛð-ɛ̀
    - - kɜc[ɔi]
      - kɜc-ì
    - - ilɛð[ɔɔ]
      - ilɛð-ɛ̀
