kind: Rules
rules:
  - _ref: coalesce_before_i
    string_map:
    - - '{<V_Mid><V_Low>}{[TBU]<T>}?i'
      - ɛ
    - - <Boundary>?{<V_Mid><V_Low>}{[TBU]<T>}?-i
      - -ɛ
    - - <Boundary>?{<V_Mid><V_Low>}{[TBU]<T>}?=i
      - =ɛ
    test_mappings:
    - - ka-i
      - k-ɛ
    - - pɔ́-ì
      - p-ɛ̀
    - - kɜ̀-í
      - k-ɛ́
    - - pu-ì
      - pu-ì
  - _ref: delete_vowel_before_vowel
    input_pattern: <Boundary>?<V>{[TBU]<T>}?
    output_pattern: <Empty>
    right_context: <Boundary>?<V>
    test_mappings:
    - - áɛ̀
      - ɛ̀
    - - î=ǔ
      - =ǔ
    - - ɔ̀í
      - í
  - _ref: resolve_hiatus
    rule_sequence:
    - $coalesce_before_i
    - $delete_vowel_before_vowel
    test_mappings:
    - - áɛ̀
      - ɛ̀
    - - î=ǔ
      - =ǔ
    - - ɔ̀í
      - ɛ́
    - - ka-i
      - k-ɛ
    - - pɔ́-ì
      - p-ɛ̀
    - - kɜ̀-í
      - k-ɛ́
    - - p-ì
      - p-ì
