kind: FeatureMarkers
feature: class_marker
global_order: class_marking
markers:
  l:
  - type: replace
    value:
    - '[CL]'
    - l
  g:
  - type: replace
    value:
    - '[CL]'
    - k
  r:
  - type: replace
    value:
    - '[CL]'
    - r
  ð:
  - type: replace
    value:
    - '[CL]'
    - ð
  n:
  - type: replace
    value:
    - '[CL]'
    - n
  ɲ:
  - type: replace
    value:
    - '[CL]'
    - ɲ
  j:
  - type: replace
    value:
    - '[CL]'
    - j
  s:
  - type: replace
    value:
    - '[CL]'
    - s
  t̪:
  - type: replace
    value:
    - '[CL]'
    - t̪
  c:
  - type: replace
    value:
    - '[CL]'
    - c
