kind: Paradigm
part_of_speech: verb
order: [root_tone, final_vowel, argument_marker, class_prefix, resolve_hiatus, vowel_harmony, tone_processes]
global_markers:
  - rule: "$hl_star_tone"
    order: root_tone
  - rule: "$final_vowel_A"
    order: final_vowel
  - rule: "$resolve_hiatus"
    order: resolve_hiatus
  - rule: "$vowel_harmony"
    order: vowel_harmony
  - rule: "$float_tones"
    order: tone_processes
features:
  class_marker: "$class_prefixes"
  deixis: itive
  object: "$ipfv_object_markers"
  tam: imperfective
feature_combinations: ["$ipfv_feature_set"]
contingent_features:
  "subject&class_marker": "$ipfv_subject_markers"
  "subject&object": "$ipfv_3object_markers"
