kind: MorphemeSet
features:
- fv_class
- tam
- deixis
data:
# ventive imperfective
- features:
    fv_class: aɔ
    tam: imperfective
    deixis: ventive
  morpheme: -ɔ́
- features:
    fv_class: ɔɔ
    tam: imperfective
    deixis: ventive
  morpheme: -ɔ́
- features:
    fv_class: ao
    tam: imperfective
    deixis: ventive
  morpheme: -ó
- features:
    fv_class: ɔu
    tam: imperfective
    deixis: ventive
  morpheme: -ú
- features:
    fv_class: ao
    tam: imperfective
    deixis: ventive
  morpheme: -í
- features:
    fv_class: ɔu
    tam: imperfective
    deixis: ventive
  morpheme: -í
# ventive perfective
- features:
    fv_class: aɔ
    tam: perfective
    deixis: ventive
  morpheme: -ɔ́
- features:
    fv_class: ɔɔ
    tam: perfective
    deixis: ventive
  morpheme: -ɔ́
- features:
    fv_class: ao
    tam: perfective
    deixis: ventive
  morpheme: -ó
- features:
    fv_class: ɔu
    tam: perfective
    deixis: ventive
  morpheme: -ú
- features:
    fv_class: ao
    tam: perfective
    deixis: ventive
  morpheme: -í
- features:
    fv_class: ɔu
    tam: perfective
    deixis: ventive
  morpheme: -í
# itive imperfective
- features:
    fv_class: aɔ
    tam: imperfective
    deixis: itive
  morpheme: -à
- features:
    fv_class: ɔɔ
    tam: imperfective
    deixis: itive
  morpheme: -ɔ̀
- features:
    fv_class: ao
    tam: imperfective
    deixis: itive
  morpheme: -à
- features:
    fv_class: ɔu
    tam: imperfective
    deixis: itive
  morpheme: -ɔ̀
- features:
    fv_class: ao
    tam: imperfective
    deixis: itive
  morpheme: -à
- features:
    fv_class: ɔu
    tam: imperfective
    deixis: itive
  morpheme: -ɔ̀
# itive perfective
- features:
    fv_class: aɔ
    tam: perfective
    deixis: itive
  morpheme: -ɛ̀
- features:
    fv_class: ɔɔ
    tam: perfective
    deixis: itive
  morpheme: -ɛ̀
- features:
    fv_class: ao
    tam: perfective
    deixis: itive
  morpheme: -ì
- features:
    fv_class: ɔu
    tam: perfective
    deixis: itive
  morpheme: -ì
- features:
    fv_class: ao
    tam: perfective
    deixis: itive
  morpheme: -ì
- features:
    fv_class: ɔu
    tam: perfective
    deixis: itive
  morpheme: -ì