kind: MorphemeSet
features:
- plural_class
data:
- features:
    plural_class: j
  morpheme: "[pl]j-"
- features:
    plural_class: n
  morpheme: "[pl]n-"
- features:
    plural_class: r
  morpheme: "[pl]r-"
