## Tira phone inventory
# The standard Tira phone inventory consists of:
#             Labial  Dental  Alv.    Retro.  Palatal Velar
# Nasal:      m               n               ɲ       ŋ
# Stop:       p       t̪       t               c       k
#             b       d̪       d               ɟ       g
# Fricative:  f               s
#             v       ð
# Glide:      w                               j
# Lateral:                    l
# Trill:                      r      
# Tap/flap:                   ɾ       ɽ
#
# The postalveolar fricative ʃ, the glottal fricative h and the glottal stop ʔ
# are used occasionally in loanwords from English.
# Vowels:
#             Front       Central     Back
# High:       i                       u
#             ɪ                       ʊ
# Mid:        e           ə           o
#             ɛ           ɜ           ɔ
# Low:                    a
kind: Inventory
data:
  consonants:
  # the `repr` key gives a short representation for the entire class
    repr: "<C>"
    stops:
      repr: "<PLSV>"
      voiced:
        repr: "<D>"
        items: ['b', 'd̪', 'd', 'ɟ', 'g']
      voiceless:
        repr: "<T>"
        items: ['p', 't̪', 't', 'c', 'k', 'ʔ']
    nasals:
      repr: "<N>"
      items: ['m', 'n', 'ɲ', 'ŋ']
    fricatives:
      repr: "<F>"
      items: ['f', 'v', 'ð', 's', 'ʃ', 'h']
    resonants:
      repr: "<R>"
      items: ['l', 'r', 'ɾ', 'ɽ', 'j', 'w']
  vowels:
    repr: "<V>"
    high:
      repr: "<V_HIGH>"
      items: ['i', 'ɪ', 'u', 'ʊ']
    mid:
      repr: "<V_MID>"
      items: ['e', 'ɛ', 'ə', 'ɜ', 'o', 'ɔ']
    low:
      repr: "<V_LOW>"
      items: ['a']