kind: Rules
rules:
  delete_stemfinal_consonant:
    input_pattern: <C>
    output_pattern: <Empty>
    right_context: (<Boundary>{^<Boundary>}*)?#
    test_mappings:
    - - pak
      - pa
    - - pak-ta
      - pa-ta
    - - pak-a
      - pa-a
    - - pak=ta
      - pa=ta
    - - pak=a
      - pa=a
    - - pak-tar-ta
      - pak-ta-ta
    - - pak=tar-ta
      - pak=ta-ta
  final_devoice:
    string_map:
    - - g
      - k
    - - d
      - t
    - - b
      - p
    right_context: '#'
    test_mappings:
    - - pag
      - pak
    - - pak
      - pak
    - - pa
      - pa
    - - bed
      - bet
    - - bet
      - bet
    - - be
      - be
    - - rb
      - rp
    - - rp
      - rp
    - - r
      - r
  initial_mutation:
    string_map:
    - - b
      - mb
    - - d
      - nd
    - - g
      - ng
    - - r
      - nd
    - - l
      - nd
    - - j
      - nj
    - - p
      - b
    - - t
      - d
    - - k
      - g
    - - ch
      - j
    - - w
      - m
    - - y
      - nj
    left_context: '#'
    test_mappings:
    - - pet
      - bet
