kind: FeatureCombinations
features:
- tam
- deixis
- class_marker
- subject
- object
combinations:
- tam: infinitive
  class_marker: ð
- tam: imperative
  deixis:
  - itive
  - ventive
- tam:
  - imperfective
  - perfective
  deixis: '*'
  class_marker: '*'
