# Tira class prefixes
kind: FeatureMarkers
global_attributes:
  order: class_prefix
features:
  class:
  # class prefixes in Tira include: l, g, r, ð, n, ŋ, ɲ, j, s, t̪
  # assume that the slot for the class prefix, marked with <CL>,
  # is assigned at a previous stage (e.g. argument_marking)
    l:
      replace: [<CL>, l]
    g:
      replace: [<CL>, g]
    r:
      replace: [<CL>, r]
    ð:
      replace: [<CL>, ð]
    n:
      replace: [<CL>, n]
    ŋ:
      replace: [<CL>, ŋ]
    ɲ:
      replace: [<CL>, ɲ]
    j:
      replace: [<CL>, j]
    s:
      replace: [<CL>, s]
    t̪:
      replace: [<CL>, t̪]