# Imperfective auxiliary subject markers
kind: FeatureMarkers
global_attributes:
  order: argument_marker
features:
  subject:
    # singular subjects are associated with g-class
    # and plural with l-class
    # class contingencies are handled in ipfv_subj_obj_features.yaml (TODO)
    1sg:
      prefix: íŋ-<CL>-
    2sg:
      prefix: á-<CL>-
    1du.incl:
      prefix: á-<CL>-
    1pl.incl:
      prefix: á-<CL>-
    1pl.excl:
      prefix: ɲà-<CL>-
    2pl:
      prefix: ɲá-<CL>-