kind: FeatureMarkers
feature: class_marker
global_order: class_marking
markers:
  l:
  - type: replace
    value:
    - '[CL]'
    - l
  g:
  - type: replace
    value:
    - '[CL]'
    - k
  ð:
  - type: replace
    value:
    - '[CL]'
    - ð