kind: FeatureMarkers
feature: number
markers:
  singular:
  - type: rule
    value: add_class_prefix_sing
  plural:
  - type: principal_part
    value: plural_stem
  - type: rule
    value: add_class_prefix_pl
