kind: ContingentFeatureMarkers
outer_feature: tam
inner_feature: object
global_order: argument_marking
markers:
- outer_feature_value: perfective
  inner_feature_values:
    1sg:
    - type: suffix
      value: -íŋì
    2sg:
    - type: suffix
      value: -áŋà
    1dual.incl:
    - type: suffix
      value: -átɛ́
    1pl.incl:
    - type: suffix
      value: -átɛ́-r
    1pl.excl:
    - type: suffix
      value: -éɲárɛ́
    2pl:
    - type: suffix
      value: -átɛ́
