kind: ContingentFeatureMarkers
outer_feature: tam
inner_feature: subject
global_order: argument_marking
markers:
- outer_feature_value: perfective
  inner_feature_values:
    1sg:
    - type: suffix
      value: -íŋí
    2sg:
    - type: suffix
      value: -áŋá
    1dual.incl:
    - type: suffix
      value: -ɜ́llí
    1pl.incl:
    - type: suffix
      value: -ɜ́llí-r
    1pl.excl:
    - type: suffix
      value: -áɲà
    2pl:
    - type: suffix
      value: -áɲá
