kind: ContingentFeatureMarkers
outer_feature: tam
inner_feature: deixis
markers:
- outer_feature_value: imperfective
  inner_feature_values:
    itive:
    - type: rule
      value: set_hl_melody
      order: tone_melody
    - type: rule
      value: ipfv_it_fv
      order: fv_assignment
    - type: prefix
      value: '[CL]-á_'
      order: argument_marking
    ventive:
    - type: rule
      value: set_all_low_tone
      order: tone_melody
    - type: rule
      value: ipfv_pfv_vent_fv
      order: fv_assignment
    - type: prefix
      value: '[CL]-á_'
      order: argument_marking
- outer_feature_value: perfective
  inner_feature_values:
    itive:
    - type: rule
      value: set_hl_melody
      order: tone_melody
    - type: rule
      value: pfv_it_fv
      order: fv_assignment
    - type: prefix
      value: '[CL]-à_'
      order: argument_marking
    ventive:
    - type: rule
      value: set_all_low_tone
      order: tone_melody
    - type: rule
      value: ipfv_pfv_vent_fv
      order: fv_assignment
    - type: prefix
      value: '[CL]ə̀-'
      order: argument_marking
