kind: Paradigm
part_of_speech: verb
order:
- inner_suffix
- outer_suffix
global_markers:
- type: rule
  value: $harmonize_suffix
feature_markers:
  person_number: $present_tense_person_markers
  mood: $present_tense_mood_markers
  tense: present
