kind: Paradigm
part_of_speech: verb
order:
- tone_melody
- fv_assignment
- argument_marking
- class_marking
- hiatus_resolution
global_markers:
- type: rule
  value: resolve_hiatus
  order: hiatus_resolution
feature_markers:
  tam: null
  deixis: null
  class_marker: $class_markers
  subject: unmarked
  object: null
feature_combinations: $verb_obj_pro
contingent_markers:
- $object_markers
- $tam_deixis
