# cache stacks
from pynini.lib import paradigms
import os
import pynini
import hashlib
import pickle
from functools import wraps
from time import time
from typing import Any

# cache stacks
FST_CACHE = []
OUTPUT_CACHE = []
CACHE_LIMIT = os.environ.get("TIRA_PARSER_CACHE_LIMIT", 100)
PRINT_CACHE_STATS = os.environ.get("TIRA_PARSER_PRINT_CACHE_STATS", None) == "1"

def get_hashable_args_str(args, kwargs):
    """
    Arguments:
        args:   Positional arguments to be hashed.
        kwargs: Keyword arguments to be hashed.
    Returns:
        args_str:  String representation of hashable arguments.
    Raises:
        TypeError: If any argument is not hashable.
    """
    args_for_key = list(args)
    kwargs_for_key = kwargs.copy()
    for i, arg in enumerate(args):
        if type(arg) is list:
            arg = tuple(sorted(arg))
        elif type(arg) is paradigms.Paradigm:
            # Paradigm objects are not hashable, so use their name
            arg = arg.name
        args_for_key[i] = arg
        try:
            hash(arg)
        except TypeError:
            raise TypeError(f"Type {type(arg)} of arg {arg} is not hashable")
    for key, value in kwargs.items():
        if type(value) is list:
            value = tuple(sorted(value))
            kwargs_for_key[key] = value
        if type(value) is paradigms.Paradigm:
                # Paradigm objects are not hashable, so use their name
            kwargs_for_key[key] = value.name
        try:
            hash(value)
        except TypeError:
            raise TypeError(f"Type {type(value)} of kwarg {key}={value} is not hashable")
    args_str = str(args_for_key)+str(kwargs_for_key)
    return args_str


def cache_is_updated(current_file: str, cache_path: str) -> bool:
    """
    Check if the cache is updated relative to the script file.
    """
    if os.path.isdir(current_file):
        file_date = max(
            os.path.getmtime(os.path.join(current_file, f))
            for f in os.listdir(current_file)
        )
    else:
        file_date = os.path.getmtime(current_file)
    if os.path.exists(cache_path):
        cache_date = os.path.getmtime(cache_path)
        return cache_date >= file_date
    return False

def put_cached_output_on_stack(cache_path: str, output: Any) -> None:
    """
    Store cached output on the in-memory cache stack.
    """
    global OUTPUT_CACHE
    OUTPUT_CACHE.append((cache_path, output))
    if len(OUTPUT_CACHE) > CACHE_LIMIT:
        OUTPUT_CACHE.pop(0)

def put_cached_fst_on_stack(cache_path: str, fst: pynini.Fst) -> None:
    """
    Store cached FST on the in-memory cache stack.
    """
    global FST_CACHE
    FST_CACHE.append((cache_path, fst))
    if len(FST_CACHE) > CACHE_LIMIT:
        FST_CACHE.pop(0)

def get_cached_output_from_stack(cache_path: str) -> Any:
    """
    Retrieve cached output from the in-memory cache stack if available.
    """
    global OUTPUT_CACHE
    for i, (path, output) in enumerate(OUTPUT_CACHE):
        if path == cache_path:
            # Move the accessed cache to the top of the stack
            OUTPUT_CACHE.append(OUTPUT_CACHE.pop(i))
            return output
    return None

def get_cached_fst_from_stack(cache_path: str) -> pynini.Fst:
    """
    Retrieve cached FST from the in-memory cache stack if available.
    """
    global FST_CACHE
    for i, (path, fst) in enumerate(FST_CACHE):
        if path == cache_path:
            # Move the accessed cache to the top of the stack
            FST_CACHE.append(FST_CACHE.pop(i))
            return fst
    return None


def output_cache(current_file: str, cache_dir=".cache/") -> Any:
    """
    Arguments:
        current_file:  The file path of the current module.
        cache_dir:     Directory to store cached output files.
    Returns:
        out:             Python object loaded from cache or generated by the decorated function.

    Decorator that caches the output of a function returning any Python object.
    """
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            start_time = time()
            os.makedirs(cache_dir, exist_ok=True)
            try:
                args_str = get_hashable_args_str(args, kwargs)
            except TypeError as e:
                # if args are not hashable, skip caching
                if PRINT_CACHE_STATS:
                    print(
                        f"Building output for function {func.__name__} "+\
                        f"with args {args} and kwargs {kwargs} without caching (unhashable args): {e}"
                    )
                out = func(*args, **kwargs)
                end_time = time()
                if PRINT_CACHE_STATS:
                    print(f"Function {func.__name__} took {end_time - start_time} seconds")
                return out
            cache_key = hashlib.md5((func.__name__ + args_str).encode()).hexdigest()
            cache_path = os.path.join(
                cache_dir,
                f"{cache_key}.output"
            )
            cached_out = get_cached_output_from_stack(cache_path)
            if cached_out is not None:
                if PRINT_CACHE_STATS:
                    print(
                        f"Loaded output for function {func.__name__} "+\
                        f"with args {args_str} from in-memory cache"
                    )
                    end_time = time()
                    print(f"Loading from in-memory cache took {end_time - start_time} seconds")
                return cached_out
            elif cache_is_updated(current_file, cache_path):
                with open(cache_path, 'rb') as f:
                    if PRINT_CACHE_STATS:
                        print(
                            f"Loaded output for function {func.__name__} "+\
                            f"with args {args_str} from cache {cache_path}"
                        )
                    out = pickle.load(f)
                    end_time = time()
                    if PRINT_CACHE_STATS:
                        print(f"Loading cache took {end_time - start_time} seconds")
            else:
                if PRINT_CACHE_STATS:
                    print(
                        f"Building output for function {func.__name__} "+\
                        f"with args {args_str} and cache {cache_path}"
                    )
                out = func(*args, **kwargs)
                end_time = time()
                if PRINT_CACHE_STATS:
                    print(f"Function {func.__name__} took {end_time - start_time} seconds")
                with open(cache_path, 'wb') as f:
                    pickle.dump(out, f)
            put_cached_output_on_stack(cache_path, out)
            return out
        return wrapper
    return decorator


def fst_cache(current_file: str, cache_dir=".cache/", num_fst: int=1) -> pynini.Fst:
    """
    Arguments:
        current_file:  The file path of the current module.
        cache_dir:     Directory to store cached FST files.
        num_fst:        Number of FSTs returned by the decorated function.
    Returns:
        f:              FST loaded from cache or generated by the decorated function.

    Decorator that caches the output of an FST-generating function.

    """
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            os.makedirs(cache_dir, exist_ok=True)
            try:
                args_str = get_hashable_args_str(args, kwargs)
            except TypeError as e:
                # if args are not hashable, skip caching
                if PRINT_CACHE_STATS:
                    print(
                        f"Building FST for function {func.__name__} "+\
                        f"with args {args} and kwargs {kwargs} without caching (unhashable args): {e}"
                    )
                f = func(*args, **kwargs)
                return f
            cache_key = hashlib.md5((func.__name__ + args_str).encode()).hexdigest()
            cache_paths = []
            cached_fsts = []
            for i in range(num_fst):
                cache_path = os.path.join(
                    cache_dir,
                    f"{cache_key}_{i}.fst"
                )
                cache_paths.append(cache_path)
            for cache_path in cache_paths:
                cached_f = get_cached_fst_from_stack(cache_path)
                cached_fsts.append(cached_f)
            if None not in cached_fsts:
                # all FSTS found in in-memory cache
                if PRINT_CACHE_STATS:
                    print(
                        f"Loaded FST for function {func.__name__} "+\
                        f"with args {args_str} from in-memory cache"
                    )
                if num_fst == 1:
                    return cached_fsts[0]
                return cached_fsts
            elif all(cache_is_updated(current_file, cache_path) for cache_path in cache_paths):
                if PRINT_CACHE_STATS:
                    print(
                        f"Loaded FST for function {func.__name__} "+\
                        f"with args {args_str} from cache {cache_path}"
                    )
                f = [pynini.Fst.read(cache_path) for cache_path in cache_paths]
            else:
                if PRINT_CACHE_STATS:
                    print(
                        f"Building FST for function {func.__name__} "+\
                    f"with args {args_str} and cache {cache_path}"
                )
                f = func(*args, **kwargs)
                if num_fst == 1:
                    f = [f]
                for fst_obj, cache_path in zip(f, cache_paths):
                    fst_obj.write(cache_path)
                    put_cached_fst_on_stack(cache_path, fst_obj)
            if num_fst == 1:
                return f[0]
            return f
        return wrapper
    return decorator