kind: FeatureMarkers
feature: mood
global_order: inner_suffix
markers:
  indicative: null
  subjunctive:
  - type: suffix
    value: -ɔ̀k
  imperative:
  - type: rule
    value: delete_stemfinal_consonant
  infinitive:
  - type: prefix
    value: rʊ-
